// <auto-generated />
namespace Products.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UsersLogins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersLogins));
        
        string IMigrationMetadata.Id
        {
            get { return "201911032049409_UsersLogins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
